# Generated by Django 5.2.4 on 2025-07-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('INVESTOR', 'Investor'), ('ENTREPRENEUR', 'Entrepreneur')], max_length=35),
        ),
    ]
