# Generated by Django 5.2.4 on 2025-07-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('view_own_company', 'Can view own companies')]},
        ),
    ]
