# Generated by Django 5.2.4 on 2025-07-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrepreneurdetail',
            options={'permissions': [('view_own_entrepreneurdetail', 'Can view own entrepreneurdetails'), ('change_own_entrepreneurdetail', 'Can change own entrepreneurdetails'), ('delete_own_entrepreneurdetail', 'Can delete own entrepreneurdetails')]},
        ),
        migrations.AlterModelOptions(
            name='investordetail',
            options={'permissions': [('view_own_investordetail', 'Can view own investordetails'), ('change_own_investordetail', 'Can change own investordetails'), ('delete_own_investordetail', 'Can delete own investordetails')]},
        ),
    ]
