# Generated by Django 5.2.4 on 2025-07-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_entrepreneurdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('view_own_company', 'Can view own companies'), ('change_own_company', 'Can change own companies'), ('delete_own_company', 'Can delete own companies')]},
        ),
    ]
